FROM node:18-alpine as build
WORKDIR /app
COPY ../frontend-app/package.json ../frontend-app/yarn.lock ./
RUN yarn install --frozen-lockfile || yarn install
COPY ../frontend-app .
RUN yarn build

FROM node:18-alpine as prod
WORKDIR /app
RUN yarn global add serve
COPY --from=build /app/build ./build
EXPOSE 3000
CMD ["serve", "-s", "build", "-l", "3000"]
