version: '3.8'

services:
  frontend:
    build:
      context: ../frontends
      dockerfile: spring-react/Dockerfile
    container_name: spring-react-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    networks:
      - spring-react-network

  backend:
    build:
      context: ../backends
      dockerfile: spring-react/Dockerfile
    container_name: spring-react-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/modular-app
    depends_on:
      - postgres
    networks:
      - spring-react-network

  postgres:
    image: postgres:15
    container_name: spring-react-postgres
    environment:
      POSTGRES_DB: modular-app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - spring-react_postgres_data:/var/lib/postgresql/data
    networks:
      - spring-react-network

volumes:
  spring-react_postgres_data:

networks:
  spring-react-network:
    driver: bridge